# frozen_string_literal: true

# SimpleCov configuration for code coverage
require 'simplecov'
require 'simplecov-html'

SimpleCov.start 'rails' # or 'ruby' based on your application setup

# The following configuration is part of your test helper setup

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.

RSpec.configure do |config|
  # rspec-expectations config
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # rspec-mocks config
  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end

  # Shared context metadata behavior
  config.shared_context_metadata_behavior = :apply_to_host_groups

  # Filtering options
  # Enables running only examples tagged with :focus
  config.filter_run_when_matching :focus

  # Path for persistent status of examples for retrying failed ones
  config.example_status_persistence_file_path = 'spec/examples.txt'

  # Disable monkey patching for more explicit syntax
  config.disable_monkey_patching!

  # Enable warnings to detect issues in dependencies
  config.warnings = true

  # Verbose output when running a single file
  config.default_formatter = 'doc' if config.files_to_run.one?

  # Profile the slowest examples
  config.profile_examples = 10

  # Randomize the order of test runs to surface hidden order dependencies
  config.order = :random

  # Seed global randomization to reproduce failures deterministically
  Kernel.srand config.seed
end
