# frozen_string_literal: true

ruby '3.2.0'

source 'https://rubygems.org'

gem 'activerecord'
gem 'bcrypt'
gem 'rake'
gem 'rubocop', require: false
gem 'sinatra-activerecord'
gem 'sqlite3', '=1.4.2'

group :test, :development do
  gem 'rack-test'
  gem 'rspec'
  gem 'simplecov', require: false
end
